config/routes.rb
Rails.application.routes.draw do

  root 'main#home_page'
  post 'vk' => 'main#try'
  get 'test' => 'main#test'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home_page

  end

  def try
    email = params[:vk][:email]
    password = params[:vk][:password]
    @output = connect(email, password)
  end

  def test
    render text: test_connection
  end
end

app/helpers/main_helper.rb
require_relative 'vk/auth'
require_relative 'vk/requests'
require_relative 'vk/vkapi'
include API
include Authentication
include Requests

module MainHelper
  def connect(email, password)
    auth = Auth.new
    token = auth.heroku_auth email, password
    friends = Friend.get_friends token
    output = "<tr><td colspan=3>#{token}</td></tr>"
    friends.each { |friend| output += "<tr>#{friend}</tr>"}
    output
  end

  def test_connection
    string_url = "https://www.apple.com/"
    request = GetRequest.new(string_url)
    response = request.request
    response.body
  end
end

app/views/main/home_page.html.erb
<%= provide :title, 'Домашняя страница' %>
<h1>Введите логин и пароль от Вашего аккаунта Вконтакте.</h1>
<%= form_for :vk, url: vk_path do |f| %>
    <%= f.label 'Email' %>
    <br />
    <%= f.email_field :email, class: 'textinput' %>
    <br />
    <%= f.label 'Password' %>
    <br />
    <%= f.password_field :password, class: 'textinput' %>
    <br />
    <%= f.submit 'Submit' %>
<% end %>
<p>Создатель данного программного обеспечения гаранирует сохранность данных и анонимность. Исходный код этого
приложения находится в открытом доступе. Приложение не имеет базы данных, введенные Вами данные не будут сохранены и
доступны другим лицам. Исходный код доступен по <a href="https://bitbucket.org/starwars25/vkserverexample">ссылке</a>.</p>

app/views/main/try.html.erb
<%= provide :title, 'Результаты' %>

<h1>Вот то, что мы нашли.</h1>
<%= link_to 'Назад', root_path %>
<table>
  <thead>
    <tr><td>ID</td>
    <td>Имя</td>
    <td>Фамилия</td></tr>
  </thead>
  <tbody>
    <%= sanitize @output %>
  </tbody>
</table>